Dphan/performance apply property
apigear-io/template-cpp14 pull request #106
Opened 2023-07-04 13:41 UTC by dorotaphanSiili

Closes # 

## 📑 Description

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

2023-07-17 14:53 UTC, w4bremer requested changes
Only style changes.
Can you also post a perf measurement with this change?
I am curious whether the 11 % really get way better. It is still string comparison, we just don't pack it into a json struct before.
Also now having applyState and applyProperty - feels duplicate and confusing. Not sure we should keep it.
As discussed earlier, we might want to get rid of the strings altogether for a olink v2 version.

2023-07-18 10:42 UTC, dorotaphanSiili commented
all in all it wasn't 11 but ~7 - and that was visible in allocation and destruction of nlohmann. I will prepare some screens

2023-08-10 11:39 UTC, w4bremer approved these changes

2023-08-10 11:39 UTC, w4bremer commented
nice work!

2023-08-10 11:40 UTC, merged